ALTER DATABASE TfsVersionControl SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DBCC CHECKTABLE ('tbl_Version',REPAIR_ALLOW_DATA_LOSS ) WITH ALL_ERRORMSGS

ALTER DATABASE TfsVersionControl SET MULTI_USER WITH ROLLBACK IMMEDIATE