SELECT C.SESSION_ID,
       C.MOST_RECENT_SESSION_ID,
       C.CONNECT_TIME,
       C.LAST_READ,
       C.LAST_WRITE,
       C.NUM_READS,
       C.NUM_WRITES,
       C.NET_TRANSPORT,
       C.ENCRYPT_OPTION,
       C.AUTH_SCHEME,
       C.PROTOCOL_TYPE,
       C.PROTOCOL_VERSION,
       C.NET_PACKET_SIZE,
       C.ENDPOINT_ID,
       C.CLIENT_NET_ADDRESS,
       C.CLIENT_TCP_PORT,
       C.LOCAL_NET_ADDRESS,
       C.LOCAL_TCP_PORT,
       C.NODE_AFFINITY,
       C.CONNECTION_ID,
       C.PARENT_CONNECTION_ID,
       C.MOST_RECENT_SQL_HANDLE,
       CASE
           WHEN ST.DBID = 32767 THEN 'RESOURCEDB'
           ELSE DB_NAME(ST.DBID)
       END AS DATABASE_NAME,
       CASE
           WHEN ST.DBID IS NULL THEN NULL
           ELSE OBJECT_SCHEMA_NAME(ST.OBJECTID, ST.DBID)
       END AS OBJECT_SCHEMA_NAME,
       CASE
           WHEN ST.DBID IS NULL THEN NULL
           ELSE OBJECT_NAME(ST.OBJECTID, ST.DBID)
       END AS OBJECT_NAME,
       ST.TEXT AS QUERY_TEXT
FROM SYS.DM_EXEC_CONNECTIONS C CROSS APPLY SYS.DM_EXEC_SQL_TEXT(C.MOST_RECENT_SQL_HANDLE) ST
--WHERE ST.DBID=DB_id('Pegasus2008bsh')