use pegasus2008
go

select * from sys.database_query_store_options 

https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql?view=sql-server-ver15

--ALTER DATABASE [Pegasus2008] SET QUERY_STORE = ON;ALTER DATABASE ['+name+'] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, INTERVAL_LENGTH_MINUTES = 30, MAX_STORAGE_SIZE_MB = 4096, QUERY_CAPTURE_MODE = AUTO)
ALTER DATABASE pegasus2008ms  SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
ALTER DATABASE pegasus2008ms  SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
ALTER DATABASE pegasus2008ms  SET QUERY_STORE (MAX_STORAGE_SIZE_MB = 16384)
ALTER DATABASE pegasus2008bb SET QUERY_STORE ( CLEANUP_POLICY = ( STALE_QUERY_THRESHOLD_DAYS = 2 ) )

ALTER DATABASE pegasus2008bb SET QUERY_STORE (MAX_PLANS_PER_QUERY = 100)


ALTER DATABASE pegasus2008ms  SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
ALTER DATABASE [pegasus2008bb] SET QUERY_STORE = OFF


--ALTER DATABASE MyDatabase SET QUERY_STORE CLEAR; -- не проверял


USE [master]
GO
ALTER DATABASE [Pegasus2008] SET QUERY_STORE = OFF (FORCED)
GO 