USE [master]
GO

CREATE SERVER ROLE ReadOnly
GO
GRANT CONNECT ANY DATABASE TO Readonly
GO
GRANT SELECT ALL USER SECURABLES TO Readonly
GO

ALTER SERVER ROLE [Readonly] ADD MEMBER [SFN\sec_SQL_role_analytics_DC-AS-UAT]
GO

ALTER SERVER ROLE [Readonly] ADD MEMBER [SFN\sec_SQL_role_analytics_DC-AS-PrePROD]
GO

